SMB         10.129.204.177  445    DC01             [*] Windows 10.0 Build 17763 x64 (name:DC01) (domain:inlanefreight.htb) (signing:True) (SMBv1:False)
[01:10:24] ERROR    Exception while calling proto_flow() on target 10.129.204.177: [Errno Connection error (INLANEFREIGHT.HTB:88)] [Errno -2] Name or service not known                                                      connection.py:115
                    ╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/impacket/krb5/kerberosv5.py:61 in sendReceive                                                                               │                  
                    │                                                                                                                                                                                                      │                  
                    │    58 │                                                                                                                                                                                              │                  
                    │    59 │   LOG.debug('Trying to connect to KDC at %s:%s' % (targetHost, port))                                                                                                                        │                  
                    │    60 │   try:                                                                                                                                                                                       │                  
                    │ ❱  61 │   │   af, socktype, proto, canonname, sa = socket.getaddrinfo(targetHost, port, 0,                                                                                                           │                  
                    │       socket.SOCK_STREAM)[0]                                                                                                                                                                         │                  
                    │    62 │   │   s = socket.socket(af, socktype, proto)                                                                                                                                                 │                  
                    │    63 │   │   s.connect(sa)                                                                                                                                                                          │                  
                    │    64 │   except socket.error as e:                                                                                                                                                                  │                  
                    │                                                                                                                                                                                                      │                  
                    │ /usr/lib/python3.11/socket.py:962 in getaddrinfo                                                                                                                                                     │                  
                    │                                                                                                                                                                                                      │                  
                    │   959 │   # We override this function since we want to translate the numeric family                                                                                                                  │                  
                    │   960 │   # and socket type values to enum constants.                                                                                                                                                │                  
                    │   961 │   addrlist = []                                                                                                                                                                              │                  
                    │ ❱ 962 │   for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                                                                    │                  
                    │   963 │   │   af, socktype, proto, canonname, sa = res                                                                                                                                               │                  
                    │   964 │   │   addrlist.append((_intenum_converter(af, AddressFamily),                                                                                                                                │                  
                    │   965 │   │   │   │   │   │    _intenum_converter(socktype, SocketKind),                                                                                                                             │                  
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    gaierror: [Errno -2] Name or service not known                                                                                                                                                                            
                                                                                                                                                                                                                                              
                    During handling of the above exception, another exception occurred:                                                                                                                                                       
                                                                                                                                                                                                                                              
                    ╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:113 in __init__                                                                                           │                  
                    │                                                                                                                                                                                                      │                  
                    │   110 │   │   │   sleep(value)                                                                                                                                                                       │                  
                    │   111 │   │                                                                                                                                                                                          │                  
                    │   112 │   │   try:                                                                                                                                                                                   │                  
                    │ ❱ 113 │   │   │   self.proto_flow()                                                                                                                                                                  │                  
                    │   114 │   │   except Exception as e:                                                                                                                                                                 │                  
                    │   115 │   │   │   self.logger.exception(f"Exception while calling proto_flow() on target                                                                                                             │                  
                    │       {self.host}: {e}")                                                                                                                                                                             │                  
                    │   116                                                                                                                                                                                                │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:161 in proto_flow                                                                                         │                  
                    │                                                                                                                                                                                                      │                  
                    │   158 │   │   │   self.enum_host_info()                                                                                                                                                              │                  
                    │   159 │   │   │   if self.print_host_info():                                                                                                                                                         │                  
                    │   160 │   │   │   │   # because of null session                                                                                                                                                      │                  
                    │ ❱ 161 │   │   │   │   if self.login() or (self.username == "" and self.password == ""):                                                                                                              │                  
                    │   162 │   │   │   │   │   if hasattr(self.args, "module") and self.args.module:                                                                                                                      │                  
                    │   163 │   │   │   │   │   │   self.call_modules()                                                                                                                                                    │                  
                    │   164 │   │   │   │   │   else:                                                                                                                                                                      │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:424 in login                                                                                              │                  
                    │                                                                                                                                                                                                      │                  
                    │   421 │   │   if not self.args.no_bruteforce:                                                                                                                                                        │                  
                    │   422 │   │   │   for secr_index, secr in enumerate(secret):                                                                                                                                         │                  
                    │   423 │   │   │   │   for user_index, user in enumerate(username):                                                                                                                                   │                  
                    │ ❱ 424 │   │   │   │   │   if self.try_credentials(domain[user_index], user, owned[user_index],                                                                                                       │                  
                    │       secr, cred_type[secr_index], data[secr_index]):                                                                                                                                                │                  
                    │   425 │   │   │   │   │   │   owned[user_index] = True                                                                                                                                               │                  
                    │   426 │   │   │   │   │   │   if not self.args.continue_on_success:                                                                                                                                  │                  
                    │   427 │   │   │   │   │   │   │   return True                                                                                                                                                        │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:368 in try_credentials                                                                                    │                  
                    │                                                                                                                                                                                                      │                  
                    │   365 │   │   │   │   if self.args.kerberos:                                                                                                                                                         │                  
                    │   366 │   │   │   │   │   return self.kerberos_login(domain, username, secret, '', '',                                                                                                               │                  
                    │       self.kdcHost, False)                                                                                                                                                                           │                  
                    │   367 │   │   │   │   elif hasattr(self.args, "domain"):  # Some protocolls don't use domain                                                                                                         │                  
                    │       for login                                                                                                                                                                                      │                  
                    │ ❱ 368 │   │   │   │   │   return self.plaintext_login(domain, username, secret)                                                                                                                      │                  
                    │   369 │   │   │   │   elif self.args.protocol == 'ssh':                                                                                                                                              │                  
                    │   370 │   │   │   │   │   return self.plaintext_login(username, secret, data)                                                                                                                        │                  
                    │   371 │   │   │   │   else:                                                                                                                                                                          │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/protocols/ldap.py:478 in plaintext_login                                                                                │                  
                    │                                                                                                                                                                                                      │                  
                    │    475 │   │   self.domain = domain                                                                                                                                                                  │                  
                    │    476 │   │                                                                                                                                                                                         │                  
                    │    477 │   │   if self.password == "" and self.args.asreproast:                                                                                                                                      │                  
                    │ ❱  478 │   │   │   hash_tgt = KerberosAttacks(self).getTGT_asroast(self.username)                                                                                                                    │                  
                    │    479 │   │   │   if hash_tgt:                                                                                                                                                                      │                  
                    │    480 │   │   │   │   self.logger.highlight(f"{hash_tgt}")                                                                                                                                          │                  
                    │    481 │   │   │   │   with open(self.args.asreproast, "a+") as hash_asreproast:                                                                                                                     │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/protocols/ldap/kerberos.py:225 in getTGT_asroast                                                                        │                  
                    │                                                                                                                                                                                                      │                  
                    │   222 │   │   message = encoder.encode(asReq)                                                                                                                                                        │                  
                    │   223 │   │                                                                                                                                                                                          │                  
                    │   224 │   │   try:                                                                                                                                                                                   │                  
                    │ ❱ 225 │   │   │   r = sendReceive(message, domain, self.kdcHost)                                                                                                                                     │                  
                    │   226 │   │   except KerberosError as e:                                                                                                                                                             │                  
                    │   227 │   │   │   if e.getErrorCode() == constants.ErrorCodes.KDC_ERR_ETYPE_NOSUPP.value:                                                                                                            │                  
                    │   228 │   │   │   │   # RC4 not available, OK, let's ask for newer types                                                                                                                             │                  
                    │                                                                                                                                                                                                      │                  
                    │ /home/arthur/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/impacket/krb5/kerberosv5.py:65 in sendReceive                                                                               │                  
                    │                                                                                                                                                                                                      │                  
                    │    62 │   │   s = socket.socket(af, socktype, proto)                                                                                                                                                 │                  
                    │    63 │   │   s.connect(sa)                                                                                                                                                                          │                  
                    │    64 │   except socket.error as e:                                                                                                                                                                  │                  
                    │ ❱  65 │   │   raise socket.error("Connection error (%s:%s)" % (targetHost, port), e)                                                                                                                 │                  
                    │    66 │                                                                                                                                                                                              │                  
                    │    67 │   s.sendall(messageLen + data)                                                                                                                                                               │                  
                    │    68                                                                                                                                                                                                │                  
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    OSError: [Errno Connection error (INLANEFREIGHT.HTB:88)] [Errno -2] Name or service not known                                                                                                                             
Running CME against 2 targets ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
